#!/usr/bin/env bash
set -euo pipefail

readonly PROJECT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
readonly ENV_FILE="${PROJECT_DIR}/.env"
readonly GENERATOR="${PROJECT_DIR}/scripts/generate_mihomo_config.sh"
readonly RUNTIME="${PROJECT_DIR}/scripts/mihomo_runtime.sh"
readonly INSTALLER="${PROJECT_DIR}/scripts/install_mihomo.sh"
readonly SUBSCRIPTION_CHECK="${PROJECT_DIR}/scripts/subscription_check.sh"
readonly CONF_DIR="${PROJECT_DIR}/conf"
readonly CONFIG_FILE="${CONF_DIR}/config.yaml"
readonly PREVIOUS_CONFIG="${CONF_DIR}/config.yaml.previous"
readonly LOG_DIR="${PROJECT_DIR}/logs"
readonly TEMP_DIR="${PROJECT_DIR}/temp"

die() {
	printf 'ERROR: %s\n' "$*" >&2
	exit 1
}

warn() {
	printf 'WARNING: %s\n' "$*" >&2
}

secure_env_permissions() {
	local permissions
	permissions=$(stat -c '%a' "$ENV_FILE" 2>/dev/null) ||
		die "cannot inspect permissions for ${ENV_FILE}"
	if [[ "$permissions" != 600 ]]; then
		chmod 600 "$ENV_FILE" ||
			die "cannot secure permissions for ${ENV_FILE}"
		warn "fixed ${ENV_FILE} permissions (${permissions} -> 600)"
	fi
}

persist_env_secret() {
	local value=$1 candidate line replaced=false
	umask 077
	candidate=$(mktemp "${PROJECT_DIR}/.env.tmp.XXXXXX")
	while IFS= read -r line || [[ -n "$line" ]]; do
		if [[ "$line" =~ ^[[:space:]]*(export[[:space:]]+)?CLASH_SECRET= ]]; then
			if [[ "$replaced" == false ]]; then
				printf "export CLASH_SECRET='%s'\n" "$value"
				replaced=true
			fi
		else
			printf '%s\n' "$line"
		fi
	done <"$ENV_FILE" >"$candidate"
	if [[ "$replaced" == false ]]; then
		printf "export CLASH_SECRET='%s'\n" "$value" >>"$candidate"
	fi
	chmod 600 "$candidate"
	mv -f -- "$candidate" "$ENV_FILE"
}

resolve_project_path() {
	local path=$1
	if [[ "$path" == /* ]]; then
		printf '%s\n' "$path"
	else
		printf '%s/%s\n' "$PROJECT_DIR" "$path"
	fi
}

bundled_mihomo_binary() {
	case "$(uname -m 2>/dev/null || true)" in
		x86_64|amd64) printf '%s\n' "${PROJECT_DIR}/bin/clash-linux-amd64" ;;
		aarch64|arm64) printf '%s\n' "${PROJECT_DIR}/bin/clash-linux-arm64" ;;
		armv7l|armv7|arm32v7) printf '%s\n' "${PROJECT_DIR}/bin/clash-linux-armv7" ;;
	esac
}

install_proxy_helper() {
	local helper target config_root
	helper="${TEMP_DIR}/clash.sh"
	config_root="${XDG_CONFIG_HOME:-${HOME:-${TEMP_DIR}}/.config}"
	target="${CLASH_SHELL_HELPER:-${config_root}/clash-linux/shell.sh}"

	cat >"$helper" <<EOF
# Generated by clash_linux. Source this file to use the shell helpers.
proxy_on() {
	export http_proxy=http://127.0.0.1:7890
	export https_proxy=http://127.0.0.1:7890
	export no_proxy=127.0.0.1,localhost
	export HTTP_PROXY=http://127.0.0.1:7890
	export HTTPS_PROXY=http://127.0.0.1:7890
	export NO_PROXY=127.0.0.1,localhost
	echo "[ok] proxy enabled"
}

proxy_off() {
	unset http_proxy https_proxy no_proxy HTTP_PROXY HTTPS_PROXY NO_PROXY
	echo "[ok] proxy disabled"
}

proxy() {
	bash "${PROJECT_DIR}/scripts/clash_proxy-selector.sh" "\$@"
}

proxy_menu() { proxy menu; }
proxy_status() { proxy status; }
proxy_mode() { proxy mode "\$@"; }
proxy_groups() { proxy groups; }
proxy_nodes() { proxy nodes "\$@"; }
proxy_delay() { proxy delay "\$@"; }
proxy_set() { proxy set "\$@"; }
EOF

	if mkdir -p -- "$(dirname -- "$target")" 2>/dev/null &&
		install -m 0600 "$helper" "$target" 2>/dev/null; then
		printf 'Legacy shell helper installed: %s\n' "$target"
	else
		warn "cannot write ${target}; source ${helper} instead"
	fi
}

[[ -r "$ENV_FILE" ]] || die "missing ${ENV_FILE}; copy .env.example to .env first"
secure_env_permissions
# shellcheck disable=SC1090
source "$ENV_FILE"

url="${CLASH_URL:-}"
config_source="${CLASH_CONFIG_FILE:-}"
mode="${SUBSCRIPTION_MODE:-auto}"
secret="${CLASH_SECRET:-}"

if [[ -n "$url" && -n "$config_source" ]]; then
	die "CLASH_URL and CLASH_CONFIG_FILE are mutually exclusive"
fi
if [[ -z "$url" && -z "$config_source" ]]; then
	die "set either CLASH_URL or CLASH_CONFIG_FILE in .env"
fi

case "$mode" in
	auto)
		if [[ -n "$url" ]]; then
			mode=provider
		else
			mode=local-profile
		fi
		;;
	provider|local|local-profile) ;;
	*) die "SUBSCRIPTION_MODE must be auto, provider, or local-profile" ;;
esac

if [[ "$mode" == provider && -z "$url" ]]; then
	die "provider mode requires CLASH_URL"
fi
if [[ "$mode" != provider && -z "$config_source" ]]; then
	die "local-profile mode requires CLASH_CONFIG_FILE"
fi

if [[ "${secret,,}" == change-me ]]; then
	die "CLASH_SECRET uses the insecure example value change-me; run scripts/configure_env.sh or set a strong secret"
fi
if [[ -z "$secret" ]]; then
	command -v openssl >/dev/null 2>&1 || die "openssl is required to generate CLASH_SECRET"
	secret="$(openssl rand -hex 32)"
	persist_env_secret "$secret"
	export CLASH_SECRET="$secret"
	warn "CLASH_SECRET was empty; generated and persisted a random secret in ${ENV_FILE}"
fi

mkdir -p -- "$CONF_DIR" "${CONF_DIR}/ui" "$LOG_DIR" "$TEMP_DIR"
cp -a -- "${PROJECT_DIR}/dashboard/public/." "${CONF_DIR}/ui/"
chmod +x "$GENERATOR" "$RUNTIME" "$INSTALLER" "$SUBSCRIPTION_CHECK" \
	"${PROJECT_DIR}/scripts/clash_proxy-selector.sh"

configured_binary="${MIHOMO_BINARY:-}"
if [[ -n "$configured_binary" ]]; then
	MIHOMO_BINARY="$(resolve_project_path "$configured_binary")"
	export MIHOMO_BINARY
	[[ -x "$MIHOMO_BINARY" ]] ||
		die "configured MIHOMO_BINARY is not executable: ${MIHOMO_BINARY}"
elif [[ -x "$(bundled_mihomo_binary)" ]]; then
	MIHOMO_BINARY="$(bundled_mihomo_binary)"
	export MIHOMO_BINARY
elif [[ ! -x "${PROJECT_DIR}/bin/mihomo" ]]; then
	printf 'Mihomo is not installed; installing the pinned stable version...\n'
	"$INSTALLER"
fi

candidate="$(mktemp "${TEMP_DIR}/config.candidate.XXXXXX.yaml")"
cleanup() {
	if [[ -n "$candidate" ]]; then
		rm -f -- "$candidate"
	fi
}
trap cleanup EXIT HUP INT TERM

if [[ "$mode" == provider ]]; then
	generator_args=(
		provider
		--url "$url"
		--output "$candidate"
		--secret "$secret"
		--user-agent "${SUBSCRIPTION_USER_AGENT:-clash-verge/v2.5.2}"
		--interval "${SUBSCRIPTION_INTERVAL:-3600}"
		--size-limit "${SUBSCRIPTION_SIZE_LIMIT:-10485760}"
		--health-check-url "${HEALTH_CHECK_URL:-https://cp.cloudflare.com/generate_204}"
		--health-check-interval "${HEALTH_CHECK_INTERVAL:-300}"
		--health-check-timeout "${HEALTH_CHECK_TIMEOUT:-5000}"
		--controller "${MIHOMO_CONTROLLER:-127.0.0.1:9090}"
		--external-ui './ui'
	)
	if [[ -n "${SUBSCRIPTION_PROXY:-}" ]]; then
		generator_args+=(--download-proxy "$SUBSCRIPTION_PROXY")
	fi
	"$GENERATOR" "${generator_args[@]}"
else
	config_source="$(resolve_project_path "$config_source")"
	"$GENERATOR" local-profile --input "$config_source" --output "$candidate"
fi

printf 'Validating candidate configuration...\n'
MIHOMO_CONFIG="$candidate" MIHOMO_CONFIG_DIR="$CONF_DIR" "$RUNTIME" validate

# Stop only the process recorded in runtime/mihomo.pid. Unrelated processes are
# never signalled by name matching.
"$RUNTIME" stop

had_previous=false
if [[ -f "$CONFIG_FILE" ]]; then
	cp -a -- "$CONFIG_FILE" "$PREVIOUS_CONFIG"
	had_previous=true
fi
mv -f -- "$candidate" "$CONFIG_FILE"
candidate=''

printf 'Starting Mihomo...\n'
runtime_secret="${MIHOMO_API_SECRET:-}"
if [[ "$mode" == provider ]]; then
	runtime_secret="${MIHOMO_API_SECRET:-$secret}"
fi
startup_failed=false
if ! MIHOMO_API_SECRET="$runtime_secret" "$RUNTIME" start; then
	startup_failed=true
elif [[ "$mode" == provider ]]; then
	printf 'Waiting for subscription provider to become ready...\n'
	if ! MIHOMO_API_SECRET="$runtime_secret" \
		"$SUBSCRIPTION_CHECK" \
		--api-url "${MIHOMO_API_URL:-http://127.0.0.1:9090}" \
		--timeout "${SUBSCRIPTION_READY_TIMEOUT:-30}" \
		--interval "${SUBSCRIPTION_READY_INTERVAL:-1}"; then
		startup_failed=true
		"$RUNTIME" stop || true
	fi
fi

if [[ "$startup_failed" == true ]]; then
	warn "new configuration failed to start; restoring the previous configuration"
	if [[ "$had_previous" == true ]]; then
		cp -a -- "$PREVIOUS_CONFIG" "$CONFIG_FILE"
		MIHOMO_API_SECRET="${MIHOMO_API_SECRET:-}" "$RUNTIME" start || true
	else
		rm -f -- "$CONFIG_FILE"
	fi
	exit 1
fi

install_proxy_helper

printf '\nMihomo is ready.\n'
printf 'Config mode: %s\n' "$mode"
printf 'Proxy shell: ./clash shell\n'
printf 'Current shell: eval "$(./clash env)"\n'
printf 'Status: ./clash status\n'
printf 'Dashboard: ./clash dashboard\n'
