#!/usr/bin/env bash
set -euo pipefail

readonly SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
readonly PROJECT_DIR="$(cd -- "${SCRIPT_DIR}/.." && pwd)"
readonly ENV_FILE="${PROJECT_DIR}/.env"

usage() {
	cat <<EOF
Usage:
  $0 subscription URL
  $0 config FILE

Create ${ENV_FILE} with secure permissions. Running the command again changes
the configuration source while preserving the generated CLASH_SECRET.
EOF
}

die() {
	printf 'ERROR: %s\n' "$*" >&2
	exit 1
}

reject_line_breaks() {
	local label=$1 value=$2
	[[ "$value" != *$'\n'* && "$value" != *$'\r'* ]] ||
		die "${label} must not contain line breaks"
}

shell_quote() {
	local value=$1
	reject_line_breaks "configuration value" "$value"
	printf '%q' "$value"
}

generate_secret() {
	command -v openssl >/dev/null 2>&1 ||
		die "openssl is required to generate CLASH_SECRET"
	openssl rand -hex 32
}

existing_generated_secret() {
	local line value
	[[ -f "$ENV_FILE" && -r "$ENV_FILE" ]] || return 1

	while IFS= read -r line || [[ -n "$line" ]]; do
		if [[ "$line" =~ ^export[[:space:]]+CLASH_SECRET=([a-fA-F0-9]{64})[[:space:]]*$ ]]; then
			value=${BASH_REMATCH[1],,}
			printf '%s\n' "$value"
			return 0
		fi
		if [[ "$line" =~ ^export[[:space:]]+CLASH_SECRET=\'([a-fA-F0-9]{64})\'[[:space:]]*$ ]]; then
			value=${BASH_REMATCH[1],,}
			printf '%s\n' "$value"
			return 0
		fi
	done <"$ENV_FILE"
	return 1
}

absolute_file_path() {
	local path=$1 directory filename
	directory=$(dirname -- "$path")
	filename=$(basename -- "$path")
	directory=$(cd -- "$directory" 2>/dev/null && pwd -P) ||
		die "cannot resolve config directory: ${path}"
	printf '%s/%s\n' "$directory" "$filename"
}

write_env() {
	local source_type=$1 source_value=$2 secret=$3 candidate=''
	umask 077
	candidate=$(mktemp "${PROJECT_DIR}/.env.tmp.XXXXXX")
	cleanup() {
		[[ -n "$candidate" ]] && rm -f -- "$candidate"
	}
	trap cleanup EXIT HUP INT TERM

	{
		printf '# Generated by scripts/configure_env.sh. Do not commit this file.\n'
		if [[ "$source_type" == subscription ]]; then
			printf 'export CLASH_URL=%s\n' "$(shell_quote "$source_value")"
			printf "export CLASH_CONFIG_FILE=''\n"
			printf "export SUBSCRIPTION_MODE='provider'\n"
		else
			printf "export CLASH_URL=''\n"
			printf 'export CLASH_CONFIG_FILE=%s\n' "$(shell_quote "$source_value")"
			printf "export SUBSCRIPTION_MODE='local-profile'\n"
		fi
		printf 'export CLASH_SECRET=%s\n' "$(shell_quote "$secret")"
		printf "export SUBSCRIPTION_USER_AGENT='clash-verge/v2.5.2'\n"
		printf "export SUBSCRIPTION_INTERVAL='3600'\n"
		printf "export SUBSCRIPTION_PROXY=''\n"
		printf "export SUBSCRIPTION_SIZE_LIMIT='10485760'\n"
		printf "export HEALTH_CHECK_URL='https://cp.cloudflare.com/generate_204'\n"
		printf "export HEALTH_CHECK_INTERVAL='300'\n"
		printf "export HEALTH_CHECK_TIMEOUT='5000'\n"
		printf "export MIHOMO_VERSION=''\n"
		printf "export MIHOMO_SHA256=''\n"
		printf "export MIHOMO_BINARY=''\n"
		printf "export MIHOMO_ARCHIVE=''\n"
		printf "export MIHOMO_CACHE_DIR=''\n"
		printf "export MIHOMO_DOWNLOAD_PROXY=''\n"
		printf "export MIHOMO_API_URL='http://127.0.0.1:9090'\n"
		printf "export MIHOMO_CONTROLLER='127.0.0.1:9090'\n"
		printf "export MIHOMO_START_TIMEOUT='10'\n"
		printf "export MIHOMO_STOP_TIMEOUT='10'\n"
	} >"$candidate"

	chmod 600 "$candidate"
	mv -f -- "$candidate" "$ENV_FILE"
	candidate=''
	trap - EXIT HUP INT TERM
}

if [[ $# -eq 1 && ( "$1" == -h || "$1" == --help ) ]]; then
	usage
	exit 0
fi

[[ $# -eq 2 ]] || {
	usage >&2
	exit 2
}

mode=$1
source_value=$2
reject_line_breaks "source" "$source_value"

case "$mode" in
	subscription)
		[[ "$source_value" =~ ^https?://[^[:space:]]+$ ]] ||
			die "subscription URL must use http:// or https:// and contain no whitespace"
		;;
	config)
		[[ -f "$source_value" && -r "$source_value" ]] ||
			die "config must be a readable regular file: ${source_value}"
		[[ -s "$source_value" ]] ||
			die "config file is empty: ${source_value}"
		source_value=$(absolute_file_path "$source_value")
		;;
	*)
		usage >&2
		die "unknown source type: ${mode}"
		;;
esac

secret=$(existing_generated_secret || true)
if [[ -z "$secret" ]]; then
	secret=$(generate_secret)
fi

write_env "$mode" "$source_value" "$secret"
printf 'Configured %s source in %s (permissions 600).\n' "$mode" "$ENV_FILE"
