#!/usr/bin/env bash
set -euo pipefail

readonly PROJECT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
readonly CLI_PATH="${CLASH_SHELL_CLI:-${PROJECT_DIR}/clash}"
readonly BEGIN_MARKER='# >>> clash_linux shell integration >>>'
readonly END_MARKER='# <<< clash_linux shell integration <<<'
readonly BIN_DIR_NAME='.local/bin'

die() {
	printf '错误：%s\n' "$*" >&2
	exit 2
}

shell_quote() {
	local value=$1
	value=${value//\'/\'\\\'\'}
	printf "'%s'" "$value"
}

print_integration() {
	local quoted_cli
	quoted_cli=$(shell_quote "$CLI_PATH")
	cat <<EOF
# Generated by clash_linux scripts/shell_integration.sh.
_CLASH_LINUX_CLI=${quoted_cli}
_CLASH_LINUX_BIN_DIR="\${HOME}/.local/bin"
case ":\${PATH}:" in
    *:"\${_CLASH_LINUX_BIN_DIR}":*) ;;
    *) export PATH="\${_CLASH_LINUX_BIN_DIR}:\${PATH}" ;;
esac

_clash_apply_proxy_env() {
    local _clash_output _clash_status
    if _clash_output="\$("\$_CLASH_LINUX_CLI" env)"; then
        eval "\$_clash_output"
        printf '已在当前终端开启代理。\\n'
    else
        _clash_status=\$?
        printf '错误：读取代理配置失败，当前终端未修改。\\n' >&2
        return "\$_clash_status"
    fi
}

_clash_clear_proxy_env() {
    unset http_proxy https_proxy ftp_proxy all_proxy no_proxy
    unset HTTP_PROXY HTTPS_PROXY FTP_PROXY ALL_PROXY NO_PROXY
    unset socks_proxy SOCKS_PROXY rsync_proxy RSYNC_PROXY
}

clash() {
    local _clash_status
    case "\${1:-}" in
        on)
            shift
            if ((\$#)); then
                printf '错误：用法：clash on\\n' >&2
                return 2
            fi
            if "\$_CLASH_LINUX_CLI" ensure; then
                _clash_apply_proxy_env
            else
                _clash_status=\$?
                printf '当前终端代理未修改。\\n' >&2
                return "\$_clash_status"
            fi
            ;;
        off)
            shift
            if ((\$#)); then
                printf '错误：用法：clash off\\n' >&2
                return 2
            fi
            _clash_clear_proxy_env
            printf '已关闭当前终端代理；核心状态保持不变。\\n'
            ;;
        init)
            if "\$_CLASH_LINUX_CLI" "\$@"; then
                _clash_apply_proxy_env
            else
                _clash_status=\$?
                printf '当前终端代理未修改。\\n' >&2
                return "\$_clash_status"
            fi
            ;;
        uninstall)
            if "\$_CLASH_LINUX_CLI" "\$@"; then
                _clash_clear_proxy_env
                unset _CLASH_LINUX_CLI _CLASH_LINUX_BIN_DIR
                unset -f clash _clash_apply_proxy_env _clash_clear_proxy_env
                printf '已清理当前终端代理与本项目命令绑定。\\n'
            else
                _clash_status=\$?
                printf '卸载未完成，当前终端代理与命令绑定保持不变。\\n' >&2
                return "\$_clash_status"
            fi
            ;;
        stop)
            shift
            _clash_status=0
            if "\$_CLASH_LINUX_CLI" stop "\$@"; then
                printf '内核已停止，所有使用它的会话均无法继续代理；已清除当前终端代理变量。\\n'
                printf '其他 SSH 会话的代理变量仍需各自运行 clash off 清理。\\n'
            else
                _clash_status=\$?
                printf '警告：内核停止失败（退出码 %s），但已清除当前终端代理变量。\\n' "\$_clash_status" >&2
                printf '请运行 clash status 确认内核状态；其他会话的代理变量不会自动清除。\\n' >&2
            fi
            _clash_clear_proxy_env
            return "\$_clash_status"
            ;;
        *)
            "\$_CLASH_LINUX_CLI" "\$@"
            ;;
    esac
}
EOF
}

shim_content() {
    printf '%s\n' '#!/usr/bin/env sh'
    printf 'exec %s "$@"\n' "$(shell_quote "$CLI_PATH")"
}

owns_shim() {
    local shim_path="${HOME}/${BIN_DIR_NAME}/clash"
    if [[ -L "$shim_path" ]]; then
        [[ "$shim_path" -ef "$CLI_PATH" ]]
    else
        [[ -f "$shim_path" && "$(cat -- "$shim_path")" == "$(shim_content)" ]]
    fi
}

check_command_shim() {
    local shim_path="${HOME}/${BIN_DIR_NAME}/clash"
    if [[ -e "$shim_path" || -L "$shim_path" ]]; then
        owns_shim || die "${shim_path} 已被其他程序或安装占用，请保留它并先解决命令冲突。"
    fi
}

write_command_shim() {
    local bin_dir="${HOME}/${BIN_DIR_NAME}" tmp_file
    check_command_shim
    mkdir -p -- "$bin_dir"
    tmp_file=$(mktemp "${bin_dir}/.clash.XXXXXX")
    shim_content >"$tmp_file"
    chmod 0755 "$tmp_file"
    mv -f -- "$tmp_file" "${bin_dir}/clash"
    printf '已安装命令入口：%s\n' "${bin_dir}/clash"
}

remove_command_shim() {
    if owns_shim; then
        rm -- "${HOME}/${BIN_DIR_NAME}/clash"
        printf '已移除本项目命令入口。\n'
    fi
}

select_rc_file() {
	local requested=$1 shell_name
	if [[ "$requested" == auto ]]; then
		shell_name=$(basename -- "${SHELL:-bash}")
	else
		shell_name=$requested
	fi
	case "$shell_name" in
		bash) printf '%s/.bashrc' "$HOME" ;;
		zsh) printf '%s/.zshrc' "$HOME" ;;
		*) die "暂不支持 shell：${shell_name}；请使用 --shell bash 或 --shell zsh" ;;
	esac
}

loader_content() {
    local quoted_script
    quoted_script=$(shell_quote "$PROJECT_DIR/scripts/shell_integration.sh")
    printf '%s\n' "$BEGIN_MARKER"
    printf 'if [ -x %s ]; then\n' "$quoted_script"
    printf '    eval "$(%s print)"\n' "$quoted_script"
    printf 'fi\n%s\n' "$END_MARKER"
}

without_own_loader() {
    CLASH_OWN_LOADER="$(loader_content)" awk -v begin="$BEGIN_MARKER" -v end="$END_MARKER" '
        $0 == begin {
            if (buffer != "") print buffer
            buffer=$0; inside=1; next
        }
        inside {
            buffer=buffer "\n" $0
            if ($0 == end) {
                if (buffer != ENVIRON["CLASH_OWN_LOADER"]) print buffer
                buffer=""; inside=0
            }
            next
        }
        { print }
        END { if (buffer != "") print buffer }
    ' "$1"
}

rewrite_loader() {
    local rc_file=$1 action=$2 tmp_file mode=''
    [[ -e "$rc_file" ]] || [[ "$action" == install ]] || return 0
    # Preserve a user's symlinked rc rather than replacing the symlink.
    [[ ! -L "$rc_file" ]] || die "${rc_file} 是符号链接，请手动管理该文件中的 shell 集成。"
    tmp_file=$(mktemp "${rc_file}.tmp.XXXXXX")
    trap 'rm -f -- "${tmp_file:-}"' EXIT HUP INT TERM
    if [[ -e "$rc_file" ]]; then
        mode=$(stat -c '%a' "$rc_file" 2>/dev/null || stat -f '%Lp' "$rc_file" 2>/dev/null || true)
        without_own_loader "$rc_file" >"$tmp_file"
    fi
    if [[ "$action" == install ]]; then
        printf '\n' >>"$tmp_file"
        loader_content >>"$tmp_file"
    fi
    [[ -z "$mode" ]] || chmod "$mode" "$tmp_file"
    mv -f -- "$tmp_file" "$rc_file"
    trap - EXIT HUP INT TERM
}

write_loader() { rewrite_loader "$1" install; }
remove_loader() { rewrite_loader "$1" uninstall; }

usage() {
	cat <<'EOF'
用法：
  shell_integration.sh print
  shell_integration.sh install [--shell bash|zsh]
  shell_integration.sh uninstall [--shell bash|zsh]

命令：
  print      打印当前终端可 eval 加载的 clash 函数
  install    写入当前用户的 ~/.bashrc 或 ~/.zshrc，并安装 ~/.local/bin/clash
  uninstall  只移除本项目的 rc 加载块和命令入口

不会使用 sudo，不会写入 /etc。安装后重开终端即可在任意目录使用 clash；
若要立即在当前终端生效，请运行 install 输出里的 eval 命令。
EOF
}

parse_shell_option() {
	local requested=auto
	if (($#)); then
		[[ $# -eq 2 && "$1" == --shell ]] ||
			die '用法：shell_integration.sh install|uninstall [--shell bash|zsh]'
		requested=$2
	fi
	printf '%s' "$requested"
}

command_name=${1:-}
[[ -n "$command_name" ]] || {
	usage >&2
	exit 2
}
shift

case "$command_name" in
	print)
		(($# == 0)) || die '用法：shell_integration.sh print'
		print_integration
		;;
	install|uninstall)
		[[ -n ${HOME:-} && "$HOME" != / ]] ||
			die 'HOME 必须指向当前用户的家目录'
		requested_shell=$(parse_shell_option "$@")
		rc_file=$(select_rc_file "$requested_shell")
		mkdir -p -- "$HOME"
		if [[ "$command_name" == install ]]; then
			check_command_shim
			write_loader "$rc_file"
			write_command_shim
			printf '已安装 shell 集成：%s\n' "$rc_file"
			printf '重开终端后，运行 clash 添加订阅，再用 clash on 开启代理。\n'
			printf '若要立即在当前终端生效，请运行：eval "$(%s print)"\n' \
				"$(shell_quote "$PROJECT_DIR/scripts/shell_integration.sh")"
		else
			remove_loader "$rc_file"
			remove_command_shim
		fi
		;;
	-h|--help|help)
		usage
		;;
	*)
		die "未知命令：$command_name"
		;;
esac
